// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBR70uUEKW4Dj1KpdsczOSrh7EVyxl2QuI',
    appId: '1:119158268317:android:5c54d0929119479eaa8f74',
    messagingSenderId: '119158268317',
    projectId: 'arnima-8ab2f',
    storageBucket: 'arnima-8ab2f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvH4l8uuOwy_M_Q_xuncKhCFc9klTHkMY',
    appId: '1:119158268317:ios:ea4a8919d107106caa8f74',
    messagingSenderId: '119158268317',
    projectId: 'arnima-8ab2f',
    storageBucket: 'arnima-8ab2f.firebasestorage.app',
    iosBundleId: 'com.example.arnima',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSnO45ajLT2lg-qksebOXsl_KWv2l1qqw',
    appId: '1:119158268317:web:bf1362dd055dbd4daa8f74',
    messagingSenderId: '119158268317',
    projectId: 'arnima-8ab2f',
    authDomain: 'arnima-8ab2f.firebaseapp.com',
    storageBucket: 'arnima-8ab2f.firebasestorage.app',
    measurementId: 'G-H0GTSQ9367',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvH4l8uuOwy_M_Q_xuncKhCFc9klTHkMY',
    appId: '1:119158268317:ios:ea4a8919d107106caa8f74',
    messagingSenderId: '119158268317',
    projectId: 'arnima-8ab2f',
    storageBucket: 'arnima-8ab2f.firebasestorage.app',
    iosBundleId: 'com.example.arnima',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSnO45ajLT2lg-qksebOXsl_KWv2l1qqw',
    appId: '1:119158268317:web:b18ff1fa733eb591aa8f74',
    messagingSenderId: '119158268317',
    projectId: 'arnima-8ab2f',
    authDomain: 'arnima-8ab2f.firebaseapp.com',
    storageBucket: 'arnima-8ab2f.firebasestorage.app',
    measurementId: 'G-BWHBG39EX7',
  );

}